# Generated by Django 6.0.1 on 2026-02-05 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('budget_type', models.CharField(choices=[('annual', 'Annual Budget'), ('program', 'Program Budget'), ('project', 'Project Budget'), ('event', 'Event Budget')], max_length=20)),
                ('period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual'), ('project', 'Project Duration')], max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_budgets', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_budgets', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='programs.program')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='programs.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('expense_type', models.CharField(choices=[('program', 'Program Expense'), ('administrative', 'Administrative'), ('staff', 'Staff Costs'), ('transport', 'Transport & Travel'), ('equipment', 'Equipment & Supplies'), ('training', 'Training & Workshop'), ('monitoring', 'Monitoring & Evaluation'), ('other', 'Other')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_incurred', models.DateField()),
                ('paid_to', models.CharField(max_length=200)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque')], max_length=20)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='finance/expenses/receipts/')),
                ('invoice', models.FileField(blank=True, null=True, upload_to='finance/expenses/invoices/')),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('requires_chairperson_approval', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_expenses', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='programs.program')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='programs.project')),
            ],
            options={
                'ordering': ['-date_incurred'],
            },
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grant_name', models.CharField(max_length=200)),
                ('donor', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('application_date', models.DateField()),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('purpose', models.TextField()),
                ('status', models.CharField(choices=[('prospect', 'Prospect'), ('application', 'Application Submitted'), ('review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('completed', 'Completed'), ('reporting', 'Reporting')], default='prospect', max_length=20)),
                ('amount_received', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('amount_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('reporting_requirements', models.TextField(blank=True, null=True)),
                ('next_report_date', models.DateField(blank=True, null=True)),
                ('proposal', models.FileField(blank=True, null=True, upload_to='finance/grants/proposals/')),
                ('agreement', models.FileField(blank=True, null=True, upload_to='finance/grants/agreements/')),
                ('reports', models.FileField(blank=True, null=True, upload_to='finance/grants/reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('focal_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_grants', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grants', to='programs.program')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grants', to='programs.project')),
            ],
            options={
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('income_type', models.CharField(choices=[('membership_fee', 'Membership Fee'), ('donation', 'Donation'), ('grant', 'Grant'), ('fundraising', 'Fundraising'), ('project_income', 'Project Income'), ('other', 'Other')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_received', models.DateField()),
                ('received_from', models.CharField(max_length=200)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('mobile_banking', 'Mobile Banking')], max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('receipt_number', models.CharField(blank=True, max_length=100, null=True)),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='finance/income/')),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_incomes', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='programs.program')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='programs.project')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_incomes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_received'],
            },
        ),
    ]
