# Generated by Django 6.0.1 on 2026-02-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberprofile',
            options={'verbose_name': 'Member Profile', 'verbose_name_plural': 'Member Profiles'},
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='skills',
        ),
        migrations.AddField(
            model_name='customuser',
            name='data_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='education_level',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('certificate', 'Certificate'), ('diploma', 'Diploma'), ('degree', 'Degree'), ('masters', 'Masters'), ('phd', 'PhD')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='interests',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='newsletter_subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='organization_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='postal_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='referral_source',
            field=models.CharField(blank=True, choices=[('social_media', 'Social Media'), ('friend', 'Friend/Family'), ('event', 'Event/Workshop'), ('radio', 'Radio'), ('newspaper', 'Newspaper'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='events_attended',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='total_donations',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='training_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('member', 'Member'), ('farmer', 'Farmer'), ('youth', 'Youth'), ('organization', 'Organization'), ('executive', 'Executive Committee'), ('staff', 'Staff'), ('donor', 'Donor/Partner'), ('admin', 'Administrator')], default='member', max_length=20),
        ),
    ]
