# Generated by Django 6.0.1 on 2026-02-05 21:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplinaryAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('warning', 'Warning'), ('suspension', 'Suspension'), ('expulsion', 'Expulsion'), ('reprimand', 'Reprimand')], max_length=20)),
                ('grounds', models.CharField(choices=[('misconduct', 'Misconduct'), ('negligence', 'Gross Negligence'), ('insubordination', 'Insubordination'), ('abuse_of_office', 'Abuse of Office'), ('financial_impropriety', 'Financial Impropriety'), ('reputation_damage', 'Damage to Organization Reputation'), ('constitution_violation', 'Violation of Constitution')], max_length=30)),
                ('description', models.TextField()),
                ('evidence', models.TextField(blank=True, null=True)),
                ('is_summary_suspension', models.BooleanField(default=False)),
                ('suspension_start', models.DateTimeField(blank=True, null=True)),
                ('suspension_end', models.DateTimeField(blank=True, null=True)),
                ('issued_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('appeal_filed', models.BooleanField(default=False)),
                ('appeal_date', models.DateTimeField(blank=True, null=True)),
                ('appeal_details', models.TextField(blank=True, null=True)),
                ('review_committee_notes', models.TextField(blank=True, null=True)),
                ('final_decision', models.CharField(blank=True, choices=[('upheld', 'Upheld'), ('modified', 'Modified'), ('overturned', 'Overturned')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('appealed', 'Under Appeal'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_disciplinary_actions', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinary_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='GeneralAssembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('meeting_type', models.CharField(choices=[('annual', 'Annual General Meeting'), ('special', 'Special General Meeting'), ('emergency', 'Emergency Meeting')], default='annual', max_length=20)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('agenda', models.TextField()),
                ('total_attendance', models.IntegerField(default=0)),
                ('minutes_file', models.FileField(blank=True, null=True, upload_to='governance/assembly/minutes/')),
                ('attendance_sheet', models.FileField(blank=True, null=True, upload_to='governance/assembly/attendance/')),
                ('agenda_file', models.FileField(blank=True, null=True, upload_to='governance/assembly/agendas/')),
                ('is_quorum_met', models.BooleanField(default=False)),
                ('quorum_required', models.IntegerField(default=67)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chairperson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chaired_meetings', to=settings.AUTH_USER_MODEL)),
                ('members_present', models.ManyToManyField(blank=True, related_name='attended_assemblies', to=settings.AUTH_USER_MODEL)),
                ('secretary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'General Assemblies',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MembershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_membership_type', models.CharField(choices=[('ordinary', 'Ordinary Member'), ('executive', 'Executive Member'), ('honorary', 'Honorary Member')], max_length=20)),
                ('motivation_letter', models.TextField()),
                ('relevant_experience', models.TextField()),
                ('expected_contribution', models.TextField()),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('chairperson_decision', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('chairperson_comments', models.TextField(blank=True, null=True)),
                ('decision_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('supporting_documents', models.FileField(blank=True, null=True, upload_to='membership/applications/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_applications', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('resolution_type', models.CharField(choices=[('advisory', 'Advisory'), ('binding', 'Binding'), ('strategic', 'Strategic'), ('financial', 'Financial'), ('governance', 'Governance')], default='advisory', max_length=20)),
                ('votes_for', models.IntegerField(default=0)),
                ('votes_against', models.IntegerField(default=0)),
                ('votes_abstain', models.IntegerField(default=0)),
                ('chairperson_decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending Review'), ('referred', 'Referred to Committee')], default='pending', max_length=20)),
                ('chairperson_comments', models.TextField(blank=True, null=True)),
                ('decision_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('discussed', 'Under Discussion'), ('voted', 'Voted On'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('implemented', 'Implemented')], default='proposed', max_length=20)),
                ('implementation_notes', models.TextField(blank=True, null=True)),
                ('date_implemented', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('general_assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='governance.generalassembly')),
                ('proposed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_resolutions', to=settings.AUTH_USER_MODEL)),
                ('seconded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seconded_resolutions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
