# Generated by Django 6.0.1 on 2026-02-05 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('program_type', models.CharField(choices=[('agroforestry', 'Agroforestry'), ('climate_smart_ag', 'Climate-Smart Agriculture'), ('biodiversity', 'Biodiversity Conservation'), ('restoration', 'Ecosystem Restoration'), ('education', 'Environmental Education'), ('capacity', 'Capacity Building'), ('policy', 'Policy Advocacy')], max_length=30)),
                ('description', models.TextField()),
                ('objectives', models.TextField()),
                ('county', models.CharField(default='West Pokot', max_length=100)),
                ('sub_counties', models.CharField(help_text='Comma-separated list of sub-counties', max_length=500)),
                ('wards', models.CharField(blank=True, help_text='Comma-separated list of wards', max_length=500, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('duration_months', models.IntegerField(help_text='Estimated duration in months')),
                ('estimated_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('actual_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('partners', models.TextField(blank=True, help_text='List of partner organizations', null=True)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('completed', 'Completed'), ('suspended', 'Suspended')], default='planning', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='Progress percentage')),
                ('beneficiaries_target', models.IntegerField(default=0)),
                ('beneficiaries_reached', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_programs', to=settings.AUTH_USER_MODEL)),
                ('team_members', models.ManyToManyField(blank=True, related_name='programs_involved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('trees_target', models.IntegerField(default=0, help_text='Target number of trees to plant')),
                ('trees_planted', models.IntegerField(default=0)),
                ('area_coverage', models.DecimalField(decimal_places=2, default=0.0, help_text='Area in hectares', max_digits=10)),
                ('carbon_sequestration', models.DecimalField(decimal_places=2, default=0.0, help_text='Estimated CO2 sequestration in tons', max_digits=10)),
                ('gps_coordinates', models.CharField(blank=True, help_text='Latitude,Longitude', max_length=100, null=True)),
                ('land_owner', models.CharField(blank=True, max_length=200, null=True)),
                ('land_size', models.DecimalField(decimal_places=2, default=0.0, help_text='Land size in acres', max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('approved', 'Approved'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('monitoring', 'Under Monitoring')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='programs.program')),
                ('project_lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_projects', to=settings.AUTH_USER_MODEL)),
                ('volunteers', models.ManyToManyField(blank=True, related_name='volunteered_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('training_type', models.CharField(choices=[('agroforestry', 'Agroforestry Practices'), ('climate_smart', 'Climate-Smart Agriculture'), ('nursery', 'Tree Nursery Management'), ('conservation', 'Soil & Water Conservation'), ('business', 'Agribusiness'), ('leadership', 'Community Leadership')], max_length=30)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=200)),
                ('max_participants', models.IntegerField(default=30)),
                ('agenda', models.TextField(blank=True, null=True)),
                ('materials', models.FileField(blank=True, null=True, upload_to='trainings/materials/')),
                ('photos', models.ImageField(blank=True, null=True, upload_to='trainings/photos/')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('feedback_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participants', models.ManyToManyField(blank=True, related_name='attended_trainings', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='programs.program')),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_trainings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TreePlanting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_type', models.CharField(choices=[('indigenous', 'Indigenous'), ('fruit', 'Fruit Tree'), ('timber', 'Timber Tree'), ('fodder', 'Fodder Tree'), ('medicinal', 'Medicinal Tree'), ('ornamental', 'Ornamental')], max_length=20)),
                ('species', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('planting_date', models.DateField()),
                ('planting_site', models.CharField(max_length=200)),
                ('gps_coordinates', models.CharField(blank=True, max_length=100, null=True)),
                ('survival_rate', models.IntegerField(default=100, help_text='Percentage')),
                ('last_monitoring_date', models.DateField(blank=True, null=True)),
                ('monitoring_notes', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='trees/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trees_planted', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_plantings', to='programs.project')),
            ],
            options={
                'verbose_name_plural': 'Tree Plantings',
                'ordering': ['-planting_date'],
            },
        ),
    ]
